name: keqr
description: A starting point for Dart libraries or applications.
version: 1.0.0
# See LICENSE file for details.
repository: https://github.com/KevinMwita7/keqr
homepage: https://github.com/KevinMwita7/keqr
issue_tracker: https://github.com/KevinMwita7/keqr/issues

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  crclib: ^3.0.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
