name: kenya_quick_response
description: A Dart library for generating and parsing KE-QR codes, compliant with the Kenya Quick Response Code Standard 2023.
version: 1.0.0
# See LICENSE file for details.
repository: https://github.com/KevinMwita7/kenya_quick_response
homepage: https://github.com/KevinMwita7/kenya_quick_response
issue_tracker: https://github.com/KevinMwita7/kenya_quick_response/issues

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  crclib: ^3.0.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
